.TH PXEM2C++11 1
.SH NAME
pxem2c++11 \- Pxem\-to\-C++11 compiler
.SH SYNOPSIS
.B pxem2C++11
.IR file
>
.IR output.cpp
&&
\"
.IR path/to/C++11/compiler
.IR output.cpp
&&
\"
.IR ./a.out
.SH DESCRIPTION
.B pxem2c++11
is a naïve compiler for Pxem.
It outputs a corresponding C++11 program to standard output.

This compiler does never optimize your program
and check if your Pxem program is syntaxically correct;
if each looping command '.w', '.x', '.y', and '.z' has corresponding '.a'

.SH OPTIONS
This program does not accept any options.

.SH INTERNET RESOURCES
The repository for this software is available on following page:

https://github.com/GH-TpaeFawzen/Pxem2Cplusplus11

.SH LICENSES
Copyright (c) 2020 TpaeFawzen

This software is released under the MIT License.

http://opensource.org/licenses/mit-license.php
.\" end of pxem2c++11.1 """
